name: Scrape and transform data

on:
  workflow_dispatch:
  schedule:
    - cron: "13 * * * *"

permissions:
  contents: "write"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v5
      - name: Python setup
        run: |
          pip install pipenv
          pipenv install
      - name: Fetch
        run: |
          make --always-make packetlist.csv
      - name: Transform
        run: |
          make packetlist.json
      - name: Commit and push if changed
        run: |
          git config user.name "Automation"
          git config user.email "github-action@example.invalid"
          git add --all
          git commit --message "Data update: $(date -u)" || exit 0
          git push
